# Generated by Django 2.2.19 on 2023-10-20 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('full_name', models.CharField(max_length=255)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_function', models.CharField(choices=[('Administrativo', 'Administrativo'), ('Legal', 'Legal'), ('Ingenieria', 'Ingenieria'), ('Marketing/Ventas', 'Marketing/Ventas')], default=('Administrativo', 'Administrativo'), max_length=50)),
                ('team_role', models.CharField(choices=[('Titular', 'Titular'), ('Manager', 'Manager'), ('Miembro del Equipo', 'Miembro del Equipo'), ('Consumidor', 'Consumidor')], default=('Titular', 'Titular'), max_length=50)),
                ('telephone_number', models.CharField(max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('industria', models.CharField(choices=[('Industrial/Manufactura', 'Industrial/Manufactura'), ('Contabilidad', 'Contabilidad')], max_length=100, null=True)),
                ('color_compania', models.CharField(default='#FFFFFF', max_length=7)),
                ('carpeta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items.Carpeta')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
