# Generated by Django 2.2.19 on 2021-03-19 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('industria', models.CharField(choices=[('Industrial/Manufactura', 'Industrial/Manufactura'), ('Contabilidad', 'Contabilidad')], max_length=100, null=True)),
                ('color_compania', models.CharField(default='#FFFFFF', max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='job_function',
            field=models.CharField(choices=[('Administrativo', 'Administrativo'), ('Legal', 'Legal'), ('Ingenieria', 'Ingenieria'), ('Marketing/Ventas', 'Marketing/Ventas')], default=('Administrativo', 'Administrativo'), max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='team_role',
            field=models.CharField(choices=[('Titular', 'Titular'), ('Manager', 'Manager'), ('Miembro del Equipo', 'Miembro del Equipo'), ('Consumidor', 'Consumidor')], default=('Titular', 'Titular'), max_length=50),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.Company')),
            ],
        ),
    ]
