# Generated by Django 2.2.19 on 2023-10-20 01:54

from django.db import migrations, models
import django.db.models.deletion
import items.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carpeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('notas', models.TextField(blank=True, max_length=1000, null=True)),
                ('qr', models.ImageField(blank=True, null=True, upload_to=items.models.qr_upload_location)),
                ('parent_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.Carpeta')),
            ],
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('carpeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Carpeta')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('cantidad', models.IntegerField()),
                ('cantidad_minima', models.IntegerField(blank=True, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('notas', models.TextField(blank=True, max_length=1000, null=True)),
                ('qr', models.ImageField(blank=True, null=True, upload_to=items.models.qr_upload_location)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Carpeta')),
                ('tags', models.ManyToManyField(to='items.Etiqueta')),
            ],
        ),
    ]
