# Generated by Django 2.2.19 on 2021-03-19 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpeta',
            name='containing_dir',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='items.Carpeta'),
        ),
    ]
