# Generated by Django 2.2.19 on 2021-03-19 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_carpeta_containing_dir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpeta',
            name='containing_dir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.Carpeta'),
        ),
        migrations.AlterField(
            model_name='carpeta',
            name='tags',
            field=models.ManyToManyField(blank=True, to='items.Etiqueta'),
        ),
    ]
